apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: 2019-02-10T06:23:43Z
    generation: 1
    labels:
      run: simple-dotnetcore-deployment
    name: simple-dotnetcore-deployment
    namespace: default
    resourceVersion: "2600"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/simple-dotnetcore-deployment
    uid: 6a649dd9-2cfc-11e9-9999-42010a9e0091
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: simple-dotnetcore-deployment
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: simple-dotnetcore-deployment
      spec:
        containers:
        - image: gcr.io/sandbox-216902/simple-dotnetcore:latest
          imagePullPolicy: Always
          name: simple-dotnetcore-deployment
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2019-02-10T06:23:44Z
      lastUpdateTime: 2019-02-10T06:23:44Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: 2019-02-10T06:23:44Z
      lastUpdateTime: 2019-02-10T06:23:57Z
      message: ReplicaSet "simple-dotnetcore-deployment-54f84d4b7" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
